# Generated by Django 4.2.15 on 2025-04-01 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0008_project_allow_member_to_create_label_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Perspective",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.TextField(default="")),
                (
                    "type",
                    models.CharField(
                        choices=[("string", "String"), ("integer", "Integer"), ("boolean", "Boolean")],
                        default="string",
                        max_length=10,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="perspectives", to="projects.project"
                    ),
                ),
            ],
        ),
    ]
