# Generated by Django 4.2.15 on 2025-04-01 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("perspective", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PerspectiveField",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("string", "String"),
                            ("integer", "Integer"),
                            ("boolean", "Boolean"),
                            ("choice", "Choice"),
                        ],
                        max_length=10,
                    ),
                ),
                ("options", models.JSONField(blank=True, null=True)),
                (
                    "perspective",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="fields", to="perspective.perspective"
                    ),
                ),
            ],
        ),
    ]
